version: '3.8'

services:
  # mongodb-container:
  #   image: mongodb/mongodb-community-server:7.0.9-ubi9
  #   container_name: mongodb-container
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - app_network
  frontend:
    build: ./Frontend
    container_name: frontend-container
    ports:
      - "5173:5173"
    networks:
      - app_network

  backend:
    build: ./Backend
    container_name: backend-container
    # depends_on:
    #   - mongodb-container
    ports:
      - "8081:8081"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    external: true